
app_movimientostock:
    resource: "@AppBundle/Controller/MovimientostockController.php"
    type:     annotation



app_proveedor:
    resource: "@AppBundle/Controller/ProveedorController.php"
    type:     annotation



app_tipodocumento:
    resource: "@AppBundle/Controller/TipodocumentoController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_api:
    type:     annotation
    resource: "@AppBundle/Controller/Api"

api_login_check:
    path: /api/login_check